# Generated by Django 5.2.4 on 2025-07-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardGame", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="defender_card",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="point_change",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
