# Generated by Django 4.2.23 on 2025-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_card',
            field=models.IntegerField(null=True, verbose_name='공격자 카드'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='수비자 카드'),
        ),
    ]
