# Generated by Django 4.2.23 on 2025-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0002_alter_game_attacker_card_alter_game_defender_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='point_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
