# Generated by Django 5.2.4 on 2025-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0003_alter_game_attacker_card_alter_game_defender_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
