# Generated by Django 5.2.4 on 2025-07-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0002_alter_game_defender_card_alter_game_point_change'),
        ('cardGame', '0004_alter_ranking_rank'),
    ]

    operations = [
    ]
